package(default_visibility = ["//visibility:public"])

cc_library(
    name = "core",
    srcs = [
        "buffer_region.cc",
        "buffer_region.hh",
        "core.hh",
        "cubic_interpolation.cc",
        "cubic_interpolation.hh",
        "grid_map.cc",
        "grid_map.hh",
        "grid_math.cc",
        "grid_math.hh",
        "polygon.cc",
        "polygon.hh",
        "type_defs.hh",
    ],
    deps = ["@eigen"],
)
