package(default_visibility = ["//visibility:public"])

cc_library(
    name = "core",
    srcs = [
        "buffer_region.cc",
        "buffer_region.hh",
        "type_defs.hh",
    ],
    deps = ["@eigen"],
)
